sudo: required
language: python
os: linux
dist: xenial
python:
 - "2.7"
 - "3.5"
 - "3.6"
 - "3.7"
env:
# See, https://docs.travis-ci.com/user/speeding-up-the-build/
# We need a balanced distribution of the tests
# Once we add and remove tests, this distribution may become unbalanced.
# Feel free to move tests around to make the running time of the jobs
# as close as possible.
#  - TESTS=test_[a-b,d-e]*
# test_crawl.py is the longest running test.
#  - TESTS=test_c*
#  - TESTS=test_[f-h]*
#  - TESTS=test_[i-z]*
  - TESTS=test_s3*
git:
  depth: 3
before_install:
  - "export DISPLAY=:99.0"
  - "export DEBUG=1"
  - "export BOTO_CONFIG=/dev/null" # https://github.com/travis-ci/travis-ci/issues/7940
install:
  - echo "y" | ./install.sh
  - pip install -r requirements.txt
before_script:
  - flake8
script:
  - pip install -r requirements-dev.txt
  - cd test
  - py.test -s -v --durations=10 $TESTS

jobs:
  include:
    language:
    python:
    env:
      - TESTS="Docker"
    services:
      - docker
    before_install:
    before_script:
    install:
    script:
      - docker build -f Dockerfile -t openwpm .
