os: linux
dist: bionic
env:
# See, https://docs.travis-ci.com/user/speeding-up-the-build/
# We need a balanced distribution of the tests
# Once we add and remove tests, this distribution may become unbalanced.
# Feel free to move tests around to make the running time of the jobs
# as close as possible.
  - TESTS=test_[a-e]*
  - TESTS=test_[f-h]*
  - TESTS=test_[i-r,t-z]*
# test_simple_commands.py is slow due to parametrization.
  - TESTS=test_[s]*
  - TESTS=node
git:
  depth: 3
before_install:
  - "export DISPLAY=:99.0"
  - "export BOTO_CONFIG=/dev/null" # https://github.com/travis-ci/travis-ci/issues/7940
install:
  # Ref: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  # Now OpenWPM installation
  - ./install.sh
  - conda activate openwpm
before_script:
  - pre-commit run --all
script:
  - if [[ "$TESTS" == "node" ]]; then
      cd automation/Extension/webext-instrumentation;
      npm test;
    else
      cd test;
      python -m pytest -s -v --durations=10 -k $TESTS;
    fi
after_success:
  - if [[ "$TESTS" == "node" ]]; then
      npm run cov:check;
    fi

jobs:
  include:
    - language:
      python:
      env:
        - TESTS="Docker"
      services:
        - docker
      before_install:
      before_script:
      install:
      script:
        - docker build -f Dockerfile -t openwpm .
        - ./.deploy-to-dockerhub.sh
