name: openwpm
channels:
    - conda-forge
dependencies:
    - python
    - beautifulsoup4
    - dill
    # - firefox-unbranded - when it's available
    - geckodriver
    - leveldb
    - multiprocess
    - nodejs
    - pandas
    - pyarrow
    - redis-py
    - s3fs
    - selenium
    - sentry-sdk
    - tabulate
    - tblib
    - wget
    - pip
      - plyvel
      - domain_utils