name: openwpm
channels:
    - anaconda
    - conda-forge
dependencies:
    - python
    - pip
    # - firefox-unbranded - when it's available
    - leveldb    
    - geckodriver
    - sasl==0.2.1  # pinned for localstack